# docker-compose.yml
# -------------------
# This file defines how to run the application using
# Docker Compose. Compose makes it easy to build the
# image, provide environment variables, and manage
# persistent volumes.

version: "3.8"  # Compose file format version

services:
  app:
    build: .            # Build the Dockerfile in the current directory
    ports:
      - "7860:7860"     # Map host port 7860 to the container
    env_file:
      - .env            # Load API keys and other settings from .env
    volumes:
      # Mount the CSV data folder as read-only so the
      # database can be created from these files
      - ./data:/app/data:ro
      # Named volume for the SQLite DB so data persists
      - db-data:/db
      # Named volume for the FAQ vector store persistence
      - vectorstore-data:/vectorstore

volumes:
  # Named volumes are stored by Docker outside the
  # container filesystem. They survive container
  # recreation and ensure data persistence.
  db-data:
  vectorstore-data:
