# docker-compose.yml
# -------------------
# This file defines how to run the application using
# Docker Compose. Compose makes it easy to build the
# image, provide environment variables, and manage
# persistent volumes.

services:
  app:  # Defines the main service (container) for the application.
    build: .            # Build the Docker image using the Dockerfile in the current directory.
    ports:
      - "7860:7860"     # Maps port 7860 on the host machine to port 7860 inside the container.
      # This allows you to access the Gradio web app at http://localhost:7860.
    env_file:
      - .env            # Loads environment variables from the .env file.
      # The .env file typically contains sensitive information like API keys or configuration settings.
    volumes:
      - ecommerce_data:/data          # Maps the named volume 'ecommerce_data' to the '/data' directory in the container.
      # This ensures that any data written to '/data' inside the container persists across restarts.
      - ecommerce_database:/database  # Maps the named volume 'ecommerce_database' to the '/database' directory in the container.
      # This is useful for storing the SQLite database file persistently.
      - ecommerce_vectorstore:/vectorstore  # Maps the named volume 'ecommerce_vectorstore' to the '/vectorstore' directory in the container.
      # This ensures that the vector store data is not lost when the container is stopped or removed.
      - ecommerce_logs:/logs  # Maps the named volume 'ecommerce_logs' to the '/logs' directory in the container.
      # This ensures that the chats are not lost when the container is stopped or removed.

volumes:
  ecommerce_data:  # Defines a named volume for persistent storage of data files.
    external: true
  ecommerce_database:  # Defines a named volume for persistent storage of the database.
    external: true
  ecommerce_vectorstore:  # Defines a named volume for persistent storage of the vector store.
    external: true
  ecommerce_logs:  # Defines a named volume for persistent storage of the vector store.
    external: true
# These volumes are created automatically by Docker and can be managed using Docker commands.